app = "zom-ai-backend-eyvrtzpz"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  ALPHA_VANTAGE_API_KEY = "${ALPHA_VANTAGE_API_KEY}"
  OPENAI_API_KEY = "${OPENAI_API_KEY}"
  POLYGON_API_KEY = "${POLYGON_API_KEY}"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
